plugins {
    id 'java'
    id 'jacoco'
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.7'
    id 'com.enonic.xp.base'
}

repositories {
    mavenCentral()
    xp.enonicRepo('dev')
}

dependencies {
    compileOnly xplibs.api.script
    implementation libs.jdbi
    implementation libs.hikaricp

    testImplementation libs.h2
    testImplementation libs.junit.jupiter
    testImplementation libs.mockito.core
    testImplementation "com.enonic.xp:testing:${xpVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly libs.graalvm.js
}

test {
    useJUnitPlatform()
}

def testGraalJs = tasks.register('testGraalJs', Test) {
    group = 'verification'
    description = 'Runs tests with the GraalJS script engine.'
    useJUnitPlatform()
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    systemProperty 'xp.script-engine', 'GraalJS'
    shouldRunAfter test
}

check.dependsOn testGraalJs

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

check.dependsOn jacocoTestReport
